[openai]
api_key = "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"


[redshift]
host='redshift-cluster-2.ct9kqx1dcuaa.ap-south-1.redshift.amazonaws.com',
port=5439,
database='datalake',
user='kumarmohit',
password='W1BbX99CjQYy'